name: Check upstream for new release
on:
  schedule:
    # check each night at 1 AM
    - cron: '00 01 * * *'
  workflow_dispatch: {}

jobs:
  check-releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # This should be LTS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Fetch existing tags
      run: git fetch --tags origin

    - id: check-version
      name: Determine upstream version
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: sindresorhus/strip-final-newline
        excludes: prerelease, draft

    - id: check-tag
      name: Check if tag exists locally
      run: |
        RELEASE=${{ steps.check-version.outputs.release }}
        echo "Latest release is: ${RELEASE}"
        if git rev-parse -q --verify "refs/tags/${RELEASE}"; then
          echo "Tag exists here"
          echo "::set-output name=tag::${RELEASE}"
        else
          echo "Tag does not exist here"
        fi

    - name: Trigger build
      if: steps.check-tag.outputs.tag
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Sync with upstream and patch
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: release
        client-payload: '{"tag":"${{steps.check-tag.outputs.tag}}"}'
