name: Patch upstream package
on:
  - workflow_dispatch
  - push

jobs:
  patch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # This should be LTS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Switch to upstream repo
      run: |
        git remote add upstream https://github.com/sindresorhus/strip-final-newline.git
        git fetch upstream
        git checkout upstream/main

    - name: Restore some of our files
      run: |
        rm -rf .github/ readme.md
        git checkout $GITHUB_REF -- .github/ readme.md

    - name: Convert to CommonJS/ESM Hybrid
      run: bash .github/make_hybrid.sh

    - name: Test that ESM import works
      run: node --input-type="module" -e 'import foo from "strip-final-newline"'
    - name: Test that require works
      run: node --input-type="commonjs" -e 'require("strip-final-newline")'
